version: "3"
#docker-compose up -d --no-deps --build flask
services:
    postgres:
        image: postgres:12.3-alpine
        restart: always
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - ./initData/:/docker-entrypoint-initdb.d/
            #- ./postgres:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4:7.1
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
            PGADMIN_LISTEN_PORT: 80
        ports:
            - 15432:80
        #volumes:
        #    - ./pgadmin:/var/lib/pgadmin
        depends_on:
            - postgres

    mongodb:
        image: mongodb/mongodb-enterprise-server:6.0.3-ubi8
        container_name: mongodb
        restart: always
        environment:
            MONGODB_INITDB_ROOT_USERNAME: ${MONGO_LOGIN}
            MONGODB_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
        ports:
            - 27017:27017
        volumes:
            - ./mongodb/:/docker-entrypoint-initdb.d/:ro

    connector:
        image: apiconnector:latest
        environment:
            - MONGO_LOGIN = ${MONGO_LOGIN}
            - MONGO_PASSWORD = ${MONGO_PASSWORD}
            - POSTGRES_USER = ${POSTGRES_USER}
            - POSTGRES_PASSWORD = ${POSTGRES_PASSWORD}
            - POSTGRES_DB = ${POSTGRES_DB}
        command: uvicorn apiconnector:app --host 0.0.0.0
        ports:
            - 8008:8000
        depends_on:
            - postgres
            - mongodb
    flask:
        image: flask:latest
        ports:
            - 80:5000
        command: python app.py
        depends_on:
            - connector
